### ISSUE TITLE
Consider only using ES5

### ISSUE THREAD

**Issue by sunesimonsen** [sindresorhus/indent-string#11]
Thanks for a useful module. I just have a question and maybe a wish. I depended on this module without noticing that is contains ES6, that luckily failed when I uglified my app. So my question is, would you consider changing this module to only use ES5 features?

I'll happily do the PR by the way.

Kind regards
Sune

**Comment by kevva** [comment]
Why? If you need it for the browser you'll need to transpile it first. This module is mainly intended for use in Node.js which support ES2015.

If you're using Webpack, check out [babel-engine-plugin](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.
