### ISSUE TITLE
Possibility to indent every line

### ISSUE THREAD

**Issue by bokub** [sindresorhus/indent-string#12]
Could it be possible to add an option to indent every line, including the blank ones ?

I would like to achieve something like this:

```bash
#   File generated with my awesome file generator
#
#   Commit number f6c23336026a8f869e51d91f33524f062196538d
#   Thu Jul 13 2017 16:42:22 GMT+0200 (CEST)
#
```

But I get this instead: 

```bash
#   File generated with my awesome file generator

#   Commit number f6c23336026a8f869e51d91f33524f062196538d
#   Thu Jul 13 2017 16:42:22 GMT+0200 (CEST)

```

I can do a PR myself if you like the idea.

**Comment by sindresorhus** [comment]
Sure, I think it would make the most sense to convert the current `indent` argument, be an options object instead, and have `indent` be an option there too. I don't want to do a major release, so need to detect whether the third argument is a string or object and do the correct thing. So the new API would be `indentString(input, [count], [options])`.

**Comment by bokub** [comment]
Great, I'm working on it :+1:
