### ISSUE TITLE
the library not pass babel, so cannot be packed in webpack

### ISSUE THREAD

**Issue by liuyuanreading** [sindresorhus/indent-string#14]
Hi, I am using indent-string library, however, the library was not babeled after npm install(still using array function in index.js), so it cannot make webpack works well(got error when webpack -p).

Is it possible to fix that?

**Comment by SamVerschueren** [comment]
It's up to you to babelify. Check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.
