### ISSUE TITLE
Don’t append a newline

### ISSUE THREAD

**Issue by tukusejssirs** [sindresorhus/indent-string#20]
I like your package, however, it appends a newline after the final line in a string. I don’t think it should change the string apart from the indentation.

**Comment by sindresorhus** [comment]
It does not. Did you meant to open this over at https://github.com/sindresorhus/indent-string-cli ?

**Comment by tukusejssirs** [comment]
Thanks for reply, @sindresorhus!

No, I use `indent-string` in Node JS.

I’ve just tested `console.log('"' + indentString('asdf', 10).replace(/\n$/, '') + '"')` and the output is as expected (`"          asdf"`), therefore it is not an issue of your package.

Sorry for opening this non-issue! :wink:
