### ISSUE TITLE
Option to apply `strip-indent` before indenting

### ISSUE THREAD

**Issue by vjpr** [sindresorhus/indent-string#21]
With template strings I usually indent them with the code. It looks nicer.

```diff
function foo() {
  const str = indent(`
+    foo bar
- foo bar
  `)
}
```

Today:

```js
function () {
  indent(stripIndent(`
    foo bar
  `))
}
```

Better:

```js
function () {
  indent(`
    foo bar
  `, 2, {stringIndent: true})
}
```

Best:

```js
function () {
  ensureIndent(`
    foo bar
  `)
}
```

Instead of combining `strip-indent` and `indent` it would be nice to just have the option on `indent`.

Downside: Separation of concerns, but I've seen similar stuff in some of your other packages.

Think of it as a declarative way to define the indentation when using a template string. "Set the indent to 2 spaces". 

Maybe another package called `ensure-indent` would be better for this functionality.

**Comment by sindresorhus** [comment]
I think you want https://github.com/sindresorhus/redent

I'll mention it in the readme.
