### ISSUE TITLE
Allow a different indent char for the end of the indent

### ISSUE THREAD

**Issue by vjpr** [sindresorhus/indent-string#23]
I am indenting with `chalk.bgGray(' ')` chars. I want to add a different char to the indent. It would be nice to still be able to use indent size properly.

<img width="535" alt="Screenshot 2023-04-12 at 3 44 59 pm" src="https://user-images.githubusercontent.com/281413/231477183-e6e2c481-3411-4098-a0f3-fe356f1c3354.png">

## Workaround

```js
const opts = {indent: c.bgGray('    ') + ' ', includeEmptyLines: true}
let readme = indentString(md, indentSize, opts)
```

**Comment by sindresorhus** [comment]
This is a bit niche and I want to keep this package focuse, so I'm unfortunately going to pass on this request. The workaround is fairly simple though.
