### ISSUE TITLE
Swap indent and count attributes

### ISSUE THREAD

**Issue by SamVerschueren** [sindresorhus/indent-string#7]
Wouldn't it make more sense to swap the `indent` and `count` attributes and use a space as default `indent` character?

```js
indentString('Foo Bar', 5);
//=> '     Foo Bar'
```

**Comment by sindresorhus** [comment]
In hindsight, yes. Similar issue: https://github.com/sindresorhus/repeating/issues/6

I guess we could do it and ES2015ify the modules at the same time. Need to do `repeating` first as it's a dependency here. PR welcome.
